name: formulario_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.25.4
  firebase_core_web: ^2.11.4
  firebase_messaging: ^14.7.16
  firebase_messaging_web: ^3.6.5
  js: ^0.6.7
  js_interop: ^0.0.1
  flutter_local_notifications: ^18.0.1
  cloud_firestore: ^4.15.4
  cloud_functions: ^4.6.5
  provider: ^6.1.1
  sqflite: ^2.3.2
  path_provider: ^2.1.2
  path: ^1.8.3
  connectivity_plus: ^5.0.2
  excel: ^2.1.0
  workmanager: ^0.5.2
  google_fonts: ^5.1.0
  cupertino_icons: ^1.0.8
  material_design_icons_flutter: ^7.0.7296
  crypto: ^3.0.3
  url_launcher: ^6.2.4
  intl: ^0.19.0
  mailer: ^6.4.1
  encrypt: ^5.0.2
  fl_chart: ^0.66.0
  universal_html: ^2.2.4
  go_router: ^13.0.0
  font_awesome_flutter: ^10.7.0
  table_calendar: ^3.0.9
  flutter_animate: ^4.5.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.2


flutter_icons:
  android: true  # Cambia "launcher_icon" por true
  ios: true
  image_path: "assets/COCEPP.png"
  adaptive_icon_background: "#ffffff"  # Opcional: añade un color de fondo
  adaptive_icon_foreground: "assets/COCEPP.png"  # Para íconos adaptables en Android
  remove_alpha_ios: true  # Elimina el canal alfa en iOS para cumplir con las políticas de la App Store

flutter:
  uses-material-design: true
  assets:
    - assets/COCEPP.png
    - assets/Cocep_.png